// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: suppliers.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSupplier = `-- name: CreateSupplier :one
INSERT INTO schm_pos.suppliers(tenant_id, code, name, phone, email, address, created_at)
VALUES ($1, $2, $3, $4, $5, $6, NOW()) RETURNING id, tenant_id, code, name, phone, email, address, created_at, updated_at, deleted_at
`

type CreateSupplierParams struct {
	TenantID pgtype.UUID
	Code     string
	Name     string
	Phone    pgtype.Text
	Email    pgtype.Text
	Address  pgtype.Text
}

func (q *Queries) CreateSupplier(ctx context.Context, arg CreateSupplierParams) (SchmPosSupplier, error) {
	row := q.db.QueryRow(ctx, createSupplier,
		arg.TenantID,
		arg.Code,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.Address,
	)
	var i SchmPosSupplier
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteSupplier = `-- name: DeleteSupplier :one
UPDATE schm_pos.suppliers
SET
    updated_at = NOW(),
    deleted_at = NOW()
WHERE id = $1 RETURNING id, tenant_id, code, name, phone, email, address, created_at, updated_at, deleted_at
`

func (q *Queries) DeleteSupplier(ctx context.Context, id pgtype.UUID) (SchmPosSupplier, error) {
	row := q.db.QueryRow(ctx, deleteSupplier, id)
	var i SchmPosSupplier
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getSupplier = `-- name: GetSupplier :one
SELECT
    id,
    tenant_id,
    code,
    name,
    phone,
    email,
    address,
    created_at,
    updated_at
FROM schm_pos.suppliers
WHERE
    id = $1 AND deleted_at iS NULL
`

type GetSupplierRow struct {
	ID        pgtype.UUID
	TenantID  pgtype.UUID
	Code      string
	Name      string
	Phone     pgtype.Text
	Email     pgtype.Text
	Address   pgtype.Text
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) GetSupplier(ctx context.Context, id pgtype.UUID) (GetSupplierRow, error) {
	row := q.db.QueryRow(ctx, getSupplier, id)
	var i GetSupplierRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSupplierByCode = `-- name: GetSupplierByCode :one
SELECT id, tenant_id, code, name, phone, email, address, created_at, updated_at, deleted_at FROM schm_pos.suppliers
WHERE code = $1 AND deleted_at IS NULL
`

func (q *Queries) GetSupplierByCode(ctx context.Context, code string) (SchmPosSupplier, error) {
	row := q.db.QueryRow(ctx, getSupplierByCode, code)
	var i SchmPosSupplier
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listSupplier = `-- name: ListSupplier :many
SELECT
    id,
    tenant_id,
    code,
    name,
    phone,
    email,
    address,
    created_at,
    updated_at
FROM schm_pos.suppliers
WHERE
    deleted_at IS NULL
    AND(
        $1::uuid IS NULL
        OR tenant_id = $1::uuid
    )
ORDER BY name
`

type ListSupplierRow struct {
	ID        pgtype.UUID
	TenantID  pgtype.UUID
	Code      string
	Name      string
	Phone     pgtype.Text
	Email     pgtype.Text
	Address   pgtype.Text
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) ListSupplier(ctx context.Context, tenantID pgtype.UUID) ([]ListSupplierRow, error) {
	rows, err := q.db.Query(ctx, listSupplier, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSupplierRow
	for rows.Next() {
		var i ListSupplierRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Code,
			&i.Name,
			&i.Phone,
			&i.Email,
			&i.Address,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreSupplier = `-- name: RestoreSupplier :one
UPDATE schm_pos.suppliers
SET 
    updated_at = NOW(),
    deleted_at = NULL
WHERE id = $1 RETURNING id, tenant_id, code, name, phone, email, address, created_at, updated_at, deleted_at
`

func (q *Queries) RestoreSupplier(ctx context.Context, id pgtype.UUID) (SchmPosSupplier, error) {
	row := q.db.QueryRow(ctx, restoreSupplier, id)
	var i SchmPosSupplier
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateSupplier = `-- name: UpdateSupplier :one
UPDATE schm_pos.suppliers
SET
    tenant_id = COALESCE($1, tenant_id),
    code = COALESCE($2, code),
    name = COALESCE($3, name),
    phone = COALESCE($4, phone),
    email = COALESCE($5, email),
    address = COALESCE($6, address),
    updated_at = NOW()
WHERE id = $7 RETURNING id, tenant_id, code, name, phone, email, address, created_at, updated_at, deleted_at
`

type UpdateSupplierParams struct {
	TenantID pgtype.UUID
	Code     pgtype.Text
	Name     pgtype.Text
	Phone    pgtype.Text
	Email    pgtype.Text
	Address  pgtype.Text
	ID       pgtype.UUID
}

func (q *Queries) UpdateSupplier(ctx context.Context, arg UpdateSupplierParams) (SchmPosSupplier, error) {
	row := q.db.QueryRow(ctx, updateSupplier,
		arg.TenantID,
		arg.Code,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.Address,
		arg.ID,
	)
	var i SchmPosSupplier
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
